---
# tasks - rhel-install-bind.yml for nerve4-bind

- name: Install Bind on Rhel 7.x
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ rhel_svc }}"
  when:
    - ansible_distribution_major_version == "7"

- name: Install Bind on Rhel 8.x / Rocky Linux
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ rhel_svc }}"
  when:
    (ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky")
